on: [push, pull_request]
name: Build and Test
jobs:
  test:
    strategy:
      matrix:
        compiler: [gdc, ldc2]
        arch: [riscv64-unknown-elf, aarch64-none-elf]
        include:
          - arch: riscv64-unknown-elf
            board: virt_riscv64
          - arch: aarch64-none-elf
            board: raspi3
          - compiler: gdc
            analyzer: analyzer=1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-1.30.0
    - uses: zyedidia/setup-knit@v1

    - name: Install plboot
      run: cd tools/plboot && go install

    # set up gnu toolchain
    - name: Install GNU toolchain
      run: |
        wget -q https://github.com/zyedidia/build-gdc/releases/download/multiplix-toolchain-2023-2-26/gnu-${{ matrix.arch }}-linux-amd64.tar.gz -O /opt/gnu.tar.gz
        mkdir /opt/gnu-toolchain && tar -xf /opt/gnu.tar.gz -C /opt/gnu-toolchain --strip-components=1
        echo "/opt/gnu-toolchain/bin" >> $GITHUB_PATH

    - name: Build (unified, no lto)
      run: knit kernel.boot.bin board=${{ matrix.board }} dc=${{ matrix.compiler }} ${{ matrix.analyzer }} lto=false unified=true

    - name: Build (not unified, no lto)
      run: knit kernel.boot.bin board=${{ matrix.board }} dc=${{ matrix.compiler }} ${{ matrix.analyzer }} lto=false unified=false
