on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-1.30.0
    - uses: zyedidia/setup-knit@v1

    - name: Install plboot
      run: cd tools/plboot && go install

    - name: Install D-scanner
      run: |
        wget -q https://www.scs.stanford.edu/~zyedidia/dscanner.tar.gz
        mkdir dscanner && tar -xf dscanner.tar.gz -C dscanner
        echo "$PWD/dscanner" >> $GITHUB_PATH

    # set up riscv64 gnu toolchain
    - name: Install RISC-V toolchain
      run: |
        wget -q https://github.com/zyedidia/build-gdc/releases/download/multiplix-toolchain-5/gnu-riscv64-unknown-elf-linux-amd64.tar.gz -O /opt/riscv.tar.gz
        mkdir /opt/riscv-toolchain && tar -xf /opt/riscv.tar.gz -C /opt/riscv-toolchain --strip-components=1
        echo "/opt/riscv-toolchain/bin" >> $GITHUB_PATH

    - name: Lint
      run: knit lint

    - name: Build
      run: knit kernel.boot.bin board=virt_riscv64 lto=false
